### PR TITLE
Handle shared dependencies being required by server dependencies

### LINKED ISSUE #66: `wally install` loads some dependencies of shared realm in the ServerPackages folder
When a server dependency depends on a shared package that is not already in `Packages._Index`, wally installs that shared package only in the `ServerPackages` folder, but the link to that shared package found inside the server dependency folder looks for the shared package in the `Packages` folder path instead.

- Main package:

  ```toml
  [package]
  name = "flamenco687/game"
  
  version = "0.0.1"
  
  registry = "https://github.com/UpliftGames/wally-index/"
  realm = "shared"
  
  [dependencies]
  Knit = "sleitnick/knit@^1"
  Signal = "sleitnick/signal@^1"
  Fusion = "elttob/fusion@0.1.1-beta"
  Promise = "evaera/promise@3"
  Maid = "flamenco687/maid@^1"
  Proxy = "flamenco687/roblox-proxy@^1"
  
  [server-dependencies]
  Bank = "flamenco687/bank@^1.0.0-beta"
  
  [place]
  shared-packages = "game.ReplicatedStorage.Packages"
  server-packages = "game.ServerScriptService.Packages"
  ```
- Server dependency (Bank)
  ```toml
  [package]
  name = "flamenco687/bank"
  description = "Lightweight data management module/wrapper for Roblox using DataStoreService"
  
  version = "1.0.0-beta"
  license = "MIT License"
  authors = ["flamenco687"]
  
  registry = "https://github.com/UpliftGames/wally-index"
  realm = "server"
  
  exclude = [
      "test.project.json",
      "foreman.toml",
      "README.md",
      "LICENSE",
      "Exclude",
  ]
  
  [dependencies]
  TableUtil = "sleitnick/table-util@^1"
  Signal = "sleitnick/signal@^1"
  Promise = "evaera/promise@^3"
  Proxy = "flamenco687/roblox-proxy@^1"
  Error = "flamenco687/error@^1"
  Maid = "flamenco687/maid@^1"
  ```
- Shared dependency not being included in the `Packages` folder:
  ```toml
  [package]
  name = "flamenco687/error"
  description = "Roblox library to quickly throw out clean & detailed errors"
  
  version = "1.1.0"
  license = "MIT License"
  
  authors = ["flamenco687"]
  realm = "shared"
  
  registry = "https://github.com/UpliftGames/wally-index"
  
  exclude = [
      "docs", 
      "foreman.toml",
      "test.project.json",
      "README.md",
      "LICENSE"
  ]
  ```
- Link to the shared dependency that is being generated when installing Bank:
  ```lua
  return require(game.ReplicatedStorage.Packages._Index["flamenco687_error@1.1.0"]["error"])
  ```
<p align="center">

Material Bread logo

<p>

### PR DESCRIPTION
**Pull request by ddavness**
Not really the best title to this PR. Fixes #66

### CODE REVIEW

**Comment by ddavness** [comment]
Note to self - when developing on Windows make sure that the encoding of files isn't set to UTF16-LE 😬

**Comment by ddavness** [comment]
At this point two integration tests were added:
- `cross-realm-dependency` - A **shared** project which requires a **server** dependency A which in turn requires a **shared** dependency B. It is expected to **FAIL** on v0.3.1

- `cross-realm-explicit-dependency` - A **shared** project which explicitly requires A (**server**) and B (**shared**) - A also requires B. It **PASSES** on v0.3.1

**Comment by ddavness** [comment]
In a nutshell (I think):

- The resolution process will now tag all dependencies of a **server** dependency as belonging to the **server** realm of the project UNLESS one or more of these dependencies is required by a dependency on the **shared** realm - in that case those dependencies will be moved to the **shared** realm instead;
- One unit test was fixed to verify the behavior, and another one was added as a counter-example;
- Two integration tests were added to confirm the behavior;
- One of the tests is failing at the moment because the lockfile implementation doesn't seem complete yet;

**Review by magnalite — APPROVED** [review]
Amazing work on this! I have no comments and agree with all your changes. Lockfiles are now generated correctly (https://github.com/UpliftGames/wally/pull/130) so this is ready to be merged! I have updated the snap files to respect these full lockfiles correctly. Thanks for putting this together and sorry it took so long to merge.

**Pull request merged**
